### ISSUE TITLE
typescript bang operator triggers an 'expression expected' linting error

### ISSUE THREAD

**Issue by Sergeon** [prograhammer/vscode-tslint-vue#14]
When  there is a bang operator in a ts script in a `.vue` file, tslint complains about an 'expression expected':
![image](https://user-images.githubusercontent.com/6699334/38247327-2978b768-3745-11e8-8bdf-a0b8b99692a2.png)

My local setup:
* OS: MacOS High Sierra 10.13.3
* Vscode version: 1.21.1
* typescript version used by vscode: 2.7.1

related: https://github.com/kaorun343/vue-property-decorator/issues/81 
In this link, [@kaorun343](https://github.com/kaorun343) suggest that this issue may be related with the tsc version used by vscode. But I tried to pair the vscode tsc version with the node_modules tsc version and nothing changes (specifically: I pointed the `typescript.tsdk` setting to 'node_modules/typescript/lib').

How to reproduce easily:

Just a new vue-cli 3.0.0-beta.6 with typescript produce by default a `HelloWorld.vue` component (the one in the pasted screenshot, in fact) that triggers the linting error.

Thanks in advance!

**Comment by numfin** [comment]
did you solve the problem?

**Comment by Sergeon** [comment]
No @numfin, I didn't found any solution.
However, **I don't think the problem is related to tslint-vue** now. I dumbly forgot to toggle off vue-tslint before posting the issue. I did later, and the red error mark appears even without vue-tslint active.

I guess @prograhammer  should've closed this 😅 

Any hint about where should I go to get this fixed is appreciated, I don't have any idea about what is causing the issue. Is related to vetur somehow, since typescript doesn't check the file when I toggle off the vetur extension. But I have no idea if this is caused by vetur, by some vscode internals, or any other thing 😞

**Comment by numfin** [comment]
@Sergeon so i guess i should just use Vue.extend() instead of decorators untill vue team fix this ))

**Comment by Sergeon** [comment]
@numfin Well, as far as I know, this is only related to the tsc bang operator, not with @Prop itself.
