### ISSUE TITLE
Support for tsx

### ISSUE THREAD

**Issue by danieloprado** [prograhammer/vscode-tslint-vue#2]
Add support to lang=tsx

**Comment by prograhammer** [comment]
Ah, right. I will try to get to this tomorrow. 

I'm currently trying to fix a big bug where linting doesn't work on `.vue` files if they are not referenced in an `import` chain that leads up to a `.ts` file. In other words, if you were to create a `.vue` file that was no where imported in another file that eventually leads up to an import in a `.ts` file you will notice the extension will not lint that file.

**Comment by prograhammer** [comment]
I'm also working to switch the fork over to a fork of this: https://marketplace.visualstudio.com/items?itemName=eg2.ts-tslint

**Comment by prograhammer** [comment]
Alright, [v1.3.0](https://marketplace.visualstudio.com/items?itemName=prograhammer.tslint-vue) **fixes the big bug** where linting wasn't working on some .vue files (those never referenced in import statements leading back to `.ts`). Uninstall and reinstall the extension and you should be on v1.3.0.

I'm now working on `.tsx` extension. Should be ready later today.

**Comment by prograhammer** [comment]
Now supports `.tsx` in latest version (v1.3.5). Uninstall and then reinstall to get latest. Thanks!
