### ISSUE TITLE
Switching from vscode-tslint to vscode-tslint-vue makes only some tslint rules apply

### ISSUE THREAD

**Issue by dkulchenko** [prograhammer/vscode-tslint-vue#6]
Keeping a .ts file open and disabling the tslint extension and enabling vscode-tslint-vue makes most of the tslint-related red squiggles disappear for me. Some rules (like max line length 100) still work just fine, but others (such as force single quote, or require semicolons) stop being in play. Not sure how to diagnose.

My tslint.json, if relevant:

```json
{
  "defaultSeverity": "warning",
  "extends": "tslint-config-airbnb",
  "rules": {
    "import/no-extraneous-dependencies": ["error", {
      "optionalDependencies": ["test/unit/index.js"]
    }],
    "import-name": false,
    "align": [true, "parameters"],
    "quotemark": [true, "single", "avoid-escape"],
    "no-else-after-return": false
  }
}
```

**Comment by prograhammer** [comment]
Can cook up an example project to replicate this problem and send me a link here on Github? One thing to consider is that this is a fork of [vscode-tslint](https://marketplace.visualstudio.com/items?itemName=eg2.tslint). So if you disable tslint-vscode-vue and try the same file with tslint-vscode extension and the single quote or require semicolon issue doesn't work in your ts file then that means the problem is upstream.

**Comment by dkulchenko** [comment]
Sure thing - mini example project is here: https://github.com/dkulchenko/vscode-tslint-test-case

Opening up src/index.ts in VSC in that repo has proper squiggles for me with vscode-tslint enabled:

<img width="1278" alt="screen shot 2017-12-05 at 7 59 58 pm" src="https://user-images.githubusercontent.com/144206/33644015-41963510-d9f7-11e7-942e-1bc76353853b.png">

But not with vscode-tslint disabled and vscode-tslint-vue enabled:

<img width="1278" alt="screen shot 2017-12-05 at 8 00 25 pm" src="https://user-images.githubusercontent.com/144206/33644017-463568de-d9f7-11e7-841a-3ac849a5867c.png">

**Comment by dkulchenko** [comment]
(Additional note: to make this work, I am hardcoding the path to the test project's tsconfig.json in tslint-vue-1.4.2/server/server.js, as discussed in issue #5, if that changes anything.)

**Comment by prograhammer** [comment]
Yeah, if you have it hardcoded, then the example project (https://github.com/dkulchenko/vscode-tslint-test-case) will not work. You hardcoded it for a specific project, remember?

**Comment by dkulchenko** [comment]
Yep - I'm saying I hardcoded it for the example project for the purposes of the test case. No dice there :/

**Comment by prograhammer** [comment]
@dkulchenko I found out this is caused by two factors. The extension is using an older typescript version and also there's a flag missing I needed to set. So after I get back from dinner I'll release a new version that should fix this.

**Comment by prograhammer** [comment]
@dkulchenko Don't forget to find the 2 places where `workspacePath || ''` and replace the workspacePath with your hardcoded location of `tsconfig.json` (for now).

**Comment by dkulchenko** [comment]
All looks great now, thanks so much!
