### ISSUE TITLE
[tslint] Exceeds maximum line length of 100 (max-line-length)

### ISSUE THREAD

**Issue by tahq69** [prograhammer/vscode-tslint-vue#9]
After upgrading all plugins and npm I got an new issues:
`[tslint] Exceeds maximum line length of 100 (max-line-length)`

Reason:
![image](https://user-images.githubusercontent.com/7248215/34033372-a6ae1cfa-e182-11e7-88dc-7a5cb8e665ce.png)

this is from logging content in server.js

**Comment by prograhammer** [comment]
Hey again @tahq69 

So I updated the parsing to disable all tslint rules in that parsed out section. So you shouldn't have the problem anymore. Grab [v1.5.3](https://marketplace.visualstudio.com/items/prograhammer.tslint-vue/changelog) and let me know if it's working for you. Also check autofix (ie. add a semicolon and then click the lightbulb icon and autofix it) to ensure that is working. I've added tests but I don't have my Window test environment ready quite yet.

Thanks!

**Comment by tahq69** [comment]
Hi @prograhammer 

Thanks, I can confirm it is OK now.

**Comment by bbugh** [comment]
I'm having this issue on 1.5.6, autofix is also not working. All of my .vue files are saying `[tslint] Exceeds maximum line length of 120 (max-line-length)`.

**Comment by zourtney** [comment]
Any movement on this? I'm seeing this issue too.

TSlint Vue 1.5.6
TSLint 5.11.0
Typescript 3.1.4

**Comment by byrnedo** [comment]
Also seeing this.
